### ISSUE TITLE
Question about cartesian control

### ISSUE THREAD

**Issue by jc211** [TimSchneider42/franky#4]
This is an awesome fork! Thanks for sharing it. I was wondering if you've had problems with the cartesian control. Specifically, we randomly get joint acceleration and velocity discontinuity errors when using frankx. Has that been your experience too? Do you use a realtime kernel for this? 

Thanks again for the great work.

**Comment by TimSchneider42** [comment]
Hi,
glad you like this project. The discontinuity errors are a common occurrence when using cartesian control. I noticed that things got better once I switched to a Franka Research 3 and updated the firmware. 
Apart from that, you can use `robot.recover_from_errors()` to implement an automatic recovery procedure. What I did specifically was to catch the discontinuity errors, call `robot.recover_from_errors()` and autonomously moved the robot into a recovery pose with reduced dynamics.
Best,
Tim
