### ISSUE TITLE
Support for Franka Emika Research 3

### ISSUE THREAD

**Issue by CTCingithub** [TimSchneider42/franky#6]
Hi, Tim. At the very beginning, thank you for your long-time maintenance for `franky` .

Our lab currently purchased a FR3 manipulator. I wonder whether `franky` support FR3. Should  I inform the controller my robot's type? How can I realize it, just like with roslaunch command?
```
roslaunch franka_example_controller joint_impedence_control.launch robot_ip:=172.16.0.2 robot:=fr3
```

My main concern is whether `franky` will give wrong kinematical and dynamical information if I control a FR3 robot with it.

I appreciate any assistance you can provide. Thank you in advance for your help.

Best,
CTC

**Comment by TimSchneider42** [comment]
Hi,

Franky supports the FR3! We use it in our lab a lot.

There is no need to tell Franky which robot you are using; just follow the tutorial in the README to get started once you have installed it via pip: `pip install franky-panda.` 

Note that, frankly, it allows direct control of Franka robots from Python without ROS. If you need something that supports ROS, I suggest checking out the official [Franka ROS package](https://github.com/frankaemika/franka_ros).

I hope this answers your questions.

Best,
Tim

**Comment by CTCingithub** [comment]
Thank you. It works on our FR3 robot now.
